from .canvas_config import CanvasConfig
from .location_group_info_canvas import LocationGroupInfoCanvas
from .main_scene_canvas import MainSceneCanvas
from .single_neuron_plot_canvas import SingleNeuronPlotCanvas
from .widgets.plot_widgets import SingleNeuronPlotWidget
