# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and push snngine3d-nomachine-base

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true


on:
  workflow_dispatch:
    branches:
      - main
      - dev
      - 'feature/**'
      - 'features/**'
#    inputs:
#      name:
#        description: 'Image tag'
#        required: true
#        default: 'manual'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            hscprojects/snngine3d-nomachine-base
            ghcr.io/hsc-projects/snngine3d-nomachine-base
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch

#      - name: Setup Buildx
#        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "./docker/Dockerfile-SNNgine3D-nomachine-base"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
#          cache-from: type=gha
#          cache-to: type=gha,mode=max

#      - name: Trigger "Build and push snngine3d-nomachine" workflow
#        run: |
#          curl \
#          -X POST \
#          -H "Accept: application/vnd.github.v3+json" \
#          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }} \
#          https://api.github.com/repos/hsc-projects/SNNgine3D/actions/workflows/push-docker-nomachine-image/dispatches \
#          -d '{"ref":"${{ github.ref_name }}"}'
